name = "InitLoadableStruct"
uuid = "c2283afa-f45b-4432-83db-f4cc05c12624"
authors = ["Marcell <havlikmarcell@gmail.com>"]
version = "0.1.0"

[deps]
Unimplemented = "a02cd6a2-d86b-465d-8d7c-afde89aa7c79"
